server:
  port: 9001
spring:
  application:
    name: TRANSECTIONS
  datasource:
    url: jdbc:mysql://localhost:3306/compeny
    username: root
    password: Chinni@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost